algoritmo "Algoritmo 70"
// Função : Todo restaurante, embora por lei não possa obriga o cliente a pagar,
// cobra 10% para o garçom. Fazer um algoritmo que leia o valor gasto com despesas
// realizadas em um restaurante e imprima o valor total com a gorjeta.
// Autor : Maison Galvão
// Data : 11/03/2016
// Seção de Declarações 
var
v:real
inicio
escreval("Digite o valor das despesas")
leia(v)
v<-v*1.1
escreval("O valor da conta é de ",v)
fimalgoritmo
