algoritmo "Algoritmo 77"
// Função : Ler dois números reais e imprimir o quadrado da diferença do primeiro
// valor pelo segundo e a diferença dos quadrados
// Autor : Maison Galvão
// Data : 11/03/2016
// Seção de Declarações 
var
a,b:inteiro
dq,qd:real
inicio
escreval("Leia a")
leia(a)
escreval("Leia b")
leia(b)
qd <- exp((a-b),2)
dq<-exp(a,2)- exp(b,2)
escreval("O quadrado da diferença ",qd)
escreval("A diferença do quadrado ",dq)
fimalgoritmo
