algoritmo "Algoritmo 44"
// Função : Entrar com um número e a base em que se deseja calcular o logaritmo desse
// número e imprimi-lo
// Autor : Maison Galvão
// Data : 10/03/2016
// Seção de Declarações 
var
numero,base:inteiro
logaritmo:real
inicio
escreval("Entre com o número")
leia(numero)
escreval("Digite a base")
leia(base)
logaritmo<-log(numero)/log(base)
escreval("O logaritmo de ",numero," na base ",base ," = ",logaritmo)
fimalgoritmo
