algoritmo "Algoritmo 45"
// Função : Entrar com um número e imprimir a seguinte saída:
//numero:
//quadrado:
//raiz quadrada:
// Autor : Maison Galvão
// Data : 10/03/2016
// Seção de Declarações 
var
numero,quadrado,raizquadrada:real
inicio
escreval("Digite o número")
leia(numero)
quadrado<-numero*numero
raizquadrada<-numero^(1/2)
escreval("Número: ",numero)
escreval("Quadrado: ",quadrado)
escreval("Raiz Quadrada", raizquadrada)

fimalgoritmo
