algoritmo "algoritmo35"
// Função : Ler nome, endereço e telefone e imprimi-los
// Autor : Maison Galvão
// Data : 10/03/2016
// Seção de Declarações 
var
nome, endereco, telefone:caracter
inicio
// Seção de Comandos 
escreval("Digite o nome")
leia(nome)
escreval("Digite o endereço")
leia(endereco)
escreval("Digite o telefone")
leia(telefone)
escreval("")
escreval("Nome: ",nome)
escreval("Endereço: ",endereco)
escreval("Telefone: ",telefone)
fimalgoritmo
