algoritmo "Algoritmo 62"
// Função : Em épocas de pouco dinheiro, os comerciantes estão procurando aumentar
// suas vendas oferecendo desconto.Faça um algoritmo que possa entrar com o valor de
// um produto e imprima o novo valor tendo em vista que o desconto foi de 9%
// Autor : Maison Galvão
// Data : 11/03/2016
// Seção de Declarações 
var
valor:real
inicio
escreval("Digite o valor do produto")
leia(valor)
valor<-valor*0.91
escreval("O valor com desconto = ",valor)
fimalgoritmo
