algoritmo "algoritmo 36"
// Função : Ler dois números inteiros e imprimir a soma. Antes do resultado, deverá aparecer
// a mensagem: Soma
// Autor : Maison Galvão
// Data : 10/03/2016
// Seção de Declarações 
var
soma,numero1,numero2:inteiro
inicio
// Seção de Comandos 
escreval("Digite o primeiro número")
leia(numero1)
escreval("Digite o segundo número")
leia(numero2)
soma<-numero1+numero2
escreval("Soma: ",soma)
fimalgoritmo
