algoritmo "Algoritmo 65"
// Função : Calcular e apresentar o valor do volume de uma lata de óleo, utilizando
// a fórmula: volume = 3.14159 * R * altura
// Autor : Maison Galvão
// Data : 11/03/2016
// Seção de Declarações 
var
volume,altura,raio: real
inicio
escreval("Digite a altura da lata")
leia(altura)
escreval("Digite o raio da lata")
leia(raio)
volume<- pi*raio*altura
escreval("O volume da lata ",volume:4:2)
fimalgoritmo
