algoritmo "Algoritmo 5"
// Função : Fazer um bolo simples
// Autor : Maison Galvão
// Data : 30/05/2016
// Seção de Declarações 
var

inicio
// Seção de Comandos 
1 - pegar os ingridientes;
2 - se (roupa branca)
    colocar avental;
3 - se (tiver batededeira)
       bater os ingredientes;
    senão
    bater os ingredientes na mão;
4 - colocar a massa na forma;
5 - colocar a forma no forno;
6 - aguardar o tempo necessário;
7 - retirar o bolo;
fimalgoritmo
