algoritmo "algoritmo 10"
// Função : Algoritmo para levar um leão, uma cabra e um pedaço de grama de um lado
// a outro do rio, atravessando com um bote. Sabe-se que nunca o leão pode ficar
// sozinho com a cabra nem a cabra com a grama.
// Autor :
// Data : 30/05/2016
// Seção de Declarações 
var

inicio
// Seção de Comandos 
1 - Levar a grama e o leão
2 - Voltar com o leão
3 - Deixar o leão
4 - Levar a cabra
5 - Deixar a cabra
6 - Voltar com a grama
7 - Levar o leão e a grama
fimalgoritmo
