algoritmo "Algoritmo 75"
// Função : Criar um algoritmo que leia o peso de uma pessoa, só a parte inteira
// calcular e imprimir: o peso da pessoa em gramas, novo peso, em gramas, se a pessoa
// engordar 12%
// Autor : Maison Galvão
// Data : 11/03/2016
// Seção de Declarações 
var
peso:inteiro
inicio
escreval("Digite o peso")
leia(peso)
escreval("Peso em gramas ",peso*1000)
escreval("Novo peso ",peso*1.12)
fimalgoritmo
