algoritmo "Algoritmo 64"
// Função : Ler uma temperatura em graus centígrados e apresentá-la convertida em graus
// Fahrenheit. A fórmula de conversão é F=9.c+160/5 onde F é temperatura em Fahrenheit
// e C é a temperatura em centígrados.
// Autor : Maison Galvão
// Data : 11/03/2016
// Seção de Declarações 
var
c,f:real
inicio
escreval("Digite a temperatura em Celsius")
leia(c)
f<-(9*c+160)/5
escreval("A temperatura em Fahrenheit ",f)
fimalgoritmo
