algoritmo "algoritmo 8"
// Função : Jogo da forca
// Autor : Maison Galvão
// Data : 30/05/2016
// Seção de Declarações 
var

inicio
// Seção de Comandos 
1 - Escolher a palavra;
2 - montar o diagrama do jogo;
3 - enquanto((houver lacunas vazia) e (corpo imcompleto)) faça
    se (acertar uma letra)
      escrever a letra correspondente;
    senão
     desenhar uma parte do corpo na forca;
fimalgoritmo
