algoritmo "Algoritmo 57"
// Função : Entrar com as notas PR1 E PR2 em imprimir a média final:
// truncada e arredondada
// Autor : Maison Galvão
// Data : 11/03/2016
// Seção de Declarações 
var
mf,n1,n2:real
inicio
escreval("Digite a primeira nota")
leia(n1)
escreval("Digite a segunda nota")
leia(n2)
mf<-(n1+n2)/2
escreval("Média truncada ",mf:4:1)
escreval("média arredondamento ",int(mf))
fimalgoritmo
