algoritmo "Algoritmo 53"
// Função : Entrar com os lados a,b,c de um paralelepipedo. Calcular e imprimir a
// diagonal.
// Autor : Maison Galvão
// Data : 11/03/2016
// Seção de Declarações 
var
a,b,c: inteiro
inicio
escreval("Entre coma base")
leia(a)
escreval("Entre com a altura")
leia(b)
escreval("Entre com a profundidade")
leia(c)
escreval("Diagonal",raizq(exp(a,2)+exp(b,2)+ exp(c,2)))

fimalgoritmo
